name: truffle CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    #  - uses: actions/setup-java@v3
    #   with:
    #        distribution: 'corretto'
    #        java-version: '17

      - name: Run build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run detekt
        run: ./gradlew detekt